name: lh_community
description: "A new Flutter plugin."
version: 0.0.1
homepage:

environment:
  sdk: ^3.4.0
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter

  intl: any
  cupertino_icons: ^1.0.8
  flutter_bloc: ^9.1.0
  dio: ^5.8.0+1
  retrofit: ^4.4.2
  json_annotation: ^4.9.0
  package_info_plus: ^8.3.0
  flutter_svg: ^2.0.17
  event_bus: ^2.0.1
  image_picker: ^1.1.2
  flutter_gen: ^5.10.0
  extended_text:
    git:
      url: https://github.com/VB10/extended_text
      ref: fix/flutter_3.29.0
  url_launcher: ^6.3.1
  shimmer: ^3.0.0
  visibility_detector: ^0.4.0+2
  photo_view: ^0.15.0
  dismissible_page: ^1.0.2
  expandable_text: ^2.3.0
  jiffy: ^6.3.2
  flutter_image_compress: ^2.4.0
  video_compress: ^3.1.4
  video_thumbnail: ^0.5.3
  path_provider: ^2.1.5
  camerawesome: ^2.1.0
  extended_nested_scroll_view: ^6.2.1
  permission_handler: ^11.4.0
  image_gallery_saver:
    git:
      url: https://github.com/knottx/image_gallery_saver.git
      ref: knottx-latest
  file_picker: ^9.1.0
  highlight_text: ^1.8.0
  flutter_gen_runner: ^5.10.0
  retrofit_generator: ^9.1.9
  colorize: ^3.0.0
  get_it: ^8.0.3
  cached_network_image: ^3.4.1
  camera: ^0.11.1
  collection: ^1.19.1
  linkify: ^5.0.0
  flutter_exif_rotation: ^0.5.2
  photo_manager: ^3.6.4
  photo_manager_image_provider: ^2.2.0
  flick_video_player: ^0.9.0
  flutter_timezone: ^4.1.1
  timezone: ^0.10.1
  preload_page_view: ^0.2.0
  shared_preferences: ^2.5.3
  media_info: ^0.12.0+2
  video_player_android: ^2.8.13
  fc_native_image_resize: ^0.15.0
  photo_gallery:
    path: ./packages/photo_gallery


  web: ^1.0.0
  plugin_platform_interface: ^2.0.2
  device_info_plus: ^11.5.0
  app_settings: ^6.1.1
  flutter_downloader: ^1.12.0
  dropdown_button2: ^2.3.9


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.4.15
  json_serializable: ^6.8.0

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/images/
    - assets/svg/

  plugin:
    platforms:
      android:
        package: lh.community.lh_community
        pluginClass: LhCommunityPlugin
      ios:
        pluginClass: LhCommunityPlugin
      linux:
        pluginClass: LhCommunityPlugin
      macos:
        pluginClass: LhCommunityPlugin
      windows:
        pluginClass: LhCommunityPluginCApi
      web:
        pluginClass: LhCommunityWeb
        fileName: lh_community_web.dart


flutter_gen:
  output: lib/generated/
  line_length: 80
  assets:
    outputs:
      package_parameter_enabled: true
  integrations:
    flutter_svg: true
    rive: true
    lottie: true

flutter_intl:
  enabled: true
  class_name: CMS
  main_locale: ko